#!/bin/bash
clang -std=gnu99 -o enc_server enc_server.c
clang -std=gnu99 -o enc_client enc_client.c
clang -std=gnu99 -o dec_server dec_server.c
clang -std=gnu99 -o dec_client dec_client.c
clang -std=gnu99 -o keygen keygen.c